#! /bin/sh
lspci -m | while read -r line; do
    # parse lspci output: get short PCI(e) id and long description of device
	dev="${line%% *}"
	classdesc="$(echo $line | cut -d'"' -f2)"
    # join device path
	devp="/sys/bus/pci/deviced/0000:$dev"
    # control file for Runtime PM
	devc="$devp/power/control"
    # get device class
	class="$(cat "$devp/class")"
    # get device driver
	driver="$(grep '^DRIVER=[A-Za-z0-9]*$' "$1/uevent" \
		| sed 's/^DRIVER=//g' || echo "no driver")"

	if [ -f "$devc" ]; then # control file exists
        # get Runtime PM mode
		pmode="$(cat "$devc")"
        # output pm mode and device data
        printf '%s/power/control = %-4s (%s, %s, %s)\n' "$devp" "$pmode" "$class" "$classdesc" "$driver"
	else # control file missing --> output device data only
        printf '%s/power/control = (not available) (%s, %s, %s)\n' "$devp" "$class" "$classdesc" "$driver"
	fi
done
